"""PlatformIO pre-script: gzip web/index.html into src/web_assets.h (PROGMEM)."""
import gzip, os, hashlib

try:
    HERE = os.path.dirname(os.path.abspath(__file__))
except NameError:            # SCons exec()s this script without __file__
    HERE = os.path.join(os.getcwd(), "tools")
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "web", "index.html")
OUT = os.path.join(ROOT, "src", "web_assets.h")


def build():
    raw = open(SRC, "rb").read()
    gz = gzip.compress(raw, 9)
    digest = hashlib.sha256(raw).hexdigest()[:16]
    lines = ["// Generated by tools/embed_web.py — do not edit.",
             "// source: web/index.html  sha256:%s  %d B -> %d B gz" % (digest, len(raw), len(gz)),
             "#pragma once", "#include <pgmspace.h>", "",
             'static const char WEB_INDEX_ETAG[] = "%s";' % digest,
             "static const unsigned int WEB_INDEX_GZ_LEN = %d;" % len(gz),
             "static const unsigned char WEB_INDEX_GZ[] PROGMEM = {"]
    for i in range(0, len(gz), 16):
        lines.append("  " + ",".join("0x%02x" % b for b in gz[i:i + 16]) + ",")
    lines += ["};", ""]
    new = "\n".join(lines)
    if not os.path.exists(OUT) or open(OUT).read() != new:
        open(OUT, "w").write(new)
        print("embed_web: %s -> %s (%d B gzipped)" % (os.path.basename(SRC), os.path.basename(OUT), len(gz)))


build()

try:  # running under PlatformIO: rebuild whenever the HTML changes
    Import("env")  # noqa: F821
    env.Depends("$BUILD_DIR/src/main.cpp.o", SRC)  # noqa: F821
except Exception:
    pass
